### ISSUE TITLE
Error en la consola

### ISSUE THREAD

**Issue by FrancoLiberali** [taller2fiuba/hello-world-node#6]
Me tira esto cuando levanto con npm run dev
`	(node:12966) UnhandledPromiseRejectionWarning: MongooseServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017
    at new MongooseServerSelectionError (/home/franco/Documentos/facultad/taller2/hello-world-node/node_modules/mongoose/lib/error/serverSelection.js:22:11)
    at NativeConnection.Connection.openUri (/home/franco/Documentos/facultad/taller2/hello-world-node/node_modules/mongoose/lib/connection.js:823:32)
    at Mongoose.connect (/home/franco/Documentos/facultad/taller2/hello-world-node/node_modules/mongoose/lib/index.js:333:15)
    at Object.<anonymous> (/home/franco/Documentos/facultad/taller2/hello-world-node/src/db/mongoose.js:3:10)
    at Module._compile (internal/modules/cjs/loader.js:1185:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1205:10)
    at Module.load (internal/modules/cjs/loader.js:1034:32)
    at Function.Module._load (internal/modules/cjs/loader.js:923:14)
    at Module.require (internal/modules/cjs/loader.js:1074:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/franco/Documentos/facultad/taller2/hello-world-node/app.js:2:1)
    at Module._compile (internal/modules/cjs/loader.js:1185:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1205:10)
    at Module.load (internal/modules/cjs/loader.js:1034:32)
    at Function.Module._load (internal/modules/cjs/loader.js:923:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
(node:12966) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: `1)``

**Comment by edjus** [comment]
Tenés el servidor de mongo instalado y levantado?

**Comment by edjus** [comment]
@FrancoLiberali En su defecto también se puede levantar una imagen con mongo, la integración con docker para dev lo iba a resolver @sportelliluciano cuando tuviera tiempo. El comando no funciona si no tenés un servidor de mongo escuchando.
